using System;
using System.Collections.Generic;
using CitizenFX.Core;

namespace NFive.Client
{
	public static class KeyMapping
	{
		public static Dictionary<Control, Key> ControlMappings = new Dictionary<Control, Key>
		{
			// { Control.AccurateAim, Key.b_117 },
			// { Control.Aim, Key.b_101 },
			{ Control.Arrest, Key.F },
			// { Control.Attack, Key.b_100 },
			// { Control.Attack2, Key.b_100 },
			// { Control.CharacterWheel, Key.b_1015 },
			{ Control.CinematicSlowMo, Key.L },
			{ Control.Context, Key.E },
			{ Control.ContextSecondary, Key.Q },
			{ Control.Cover, Key.Q },
			// { Control.CreatorAccept, Key.b_1003 },
			// { Control.CreatorDelete, Key.b_198 },
			{ Control.CreatorLS, Key.R },
			{ Control.CreatorLT, Key.X },
			// { Control.CreatorMenuToggle, Key.b_1000 },
			{ Control.CreatorRS, Key.F },
			{ Control.CreatorRT, Key.C },
			// { Control.CursorAccept, Key.b_100 },
			// { Control.CursorCancel, Key.b_101 },
			// { Control.CursorScrollDown, Key.b_116 },
			// { Control.CursorScrollUp, Key.b_115 },
			// { Control.CursorX, Key.b_112 },
			// { Control.CursorY, Key.b_113 },
			{ Control.Detonate, Key.G },
			// { Control.Dive, Key.b_2000 },
			// { Control.DropAmmo, Key.b_179 },
			// { Control.DropWeapon, Key.b_178 },
			// { Control.Duck, Key.b_1013 },
			{ Control.Enter, Key.F },
			{ Control.EnterCheatCode, Key.Backtick },
			//{ Control.FlyLeftRight, "t_D%t_A },
			//{ Control.FlyUpDown, "t_S%t_W },
			// { Control.FrontendAccept, Key.b_1003 },
			//{ Control.FrontendAxisX, "t_D%t_A },
			//{ Control.FrontendAxisY, "t_S%t_W },
			// { Control.FrontendCancel, Key.b_199 },
			// { Control.FrontendDelete, Key.b_198 },
			// { Control.FrontendDown, Key.b_195 },
			// { Control.FrontendEndscreenAccept, Key.b_1003 },
			// { Control.FrontendEndscreenExpand, Key.b_2000 },
			{ Control.FrontendLb, Key.Q },
			// { Control.FrontendLeaderboard, Key.b_1002 },
			// { Control.FrontendLeft, Key.b_196 },
			// { Control.FrontendLs, Key.b_1000 },
			// { Control.FrontendLt, Key.b_1010 },
			{ Control.FrontendPause, Key.P },
			// { Control.FrontendPauseAlternate, Key.b_199 },
			{ Control.FrontendRb, Key.E },
			// { Control.FrontendRdown, Key.b_1003 },
			// { Control.FrontendRight, Key.b_197 },
			//{ Control.FrontendRightAxisX, "t_]%t_[ },
			// { Control.FrontendRightAxisY, Key.b_117 },
			// { Control.FrontendRleft, Key.b_2000 },
			// { Control.FrontendRright, Key.b_1004 },
			// { Control.FrontendRs, Key.b_1013 },
			// { Control.FrontendRt, Key.b_1009 },
			// { Control.FrontendRup, Key.b_1002 },
			// { Control.FrontendSelect, Key.b_1012 },
			// { Control.FrontendSocialClub, Key.b_1008 },
			// { Control.FrontendSocialClubSecondary, Key.b_1008 },
			// { Control.FrontendUp, Key.b_194 },
			// { Control.FrontendX, Key.b_2000 },
			// { Control.FrontendY, Key.b_1002 },
			{ Control.HUDSpecial, Key.Z },
			{ Control.InteractionMenu, Key.OemSemicolon },
			// { Control.Jump, Key.b_2000 },
			{ Control.LookBehind, Key.C },
			// { Control.LookDown, Key.b_995 },
			// { Control.LookDownOnly, Key.b_111 },
			// { Control.LookLeft, Key.b_995 },
			// { Control.LookLeftOnly, Key.b_108 },
			// { Control.LookLeftRight, Key.b_112 },
			// { Control.LookRight, Key.b_995 },
			// { Control.LookRightOnly, Key.b_109 },
			// { Control.LookUp, Key.b_995 },
			// { Control.LookUpDown, Key.b_113 },
			// { Control.LookUpOnly, Key.b_110 },
			// { Control.Map, Key.b_995 },
			// { Control.MapPointOfInterest, Key.b_102 },
			// { Control.MeleeAttack1, Key.b_995 },
			// { Control.MeleeAttack2, Key.b_995 },
			// { Control.MeleeAttackAlternate, Key.b_100 },
			{ Control.MeleeAttackHeavy, Key.Q },
			{ Control.MeleeAttackLight, Key.R },
			// { Control.MeleeBlock, Key.b_2000 },
			// { Control.MoveDown, Key.b_995 },
			{ Control.MoveDownOnly, Key.S },
			// { Control.MoveLeft, Key.b_995 },
			{ Control.MoveLeftOnly, Key.A },
			//{ Control.MoveLeftRight, "t_D%t_A },
			// { Control.MoveRight, Key.b_995 },
			{ Control.MoveRightOnly, Key.D },
			// { Control.MoveUp, Key.b_995 },
			//{ Control.MoveUpDown, "t_S%t_W },
			{ Control.MoveUpOnly, Key.W },
			{ Control.MpTextChatAll, Key.T },
			// { Control.MpTextChatCrew, Key.b_995 },
			// { Control.MpTextChatFriends, Key.b_995 },
			{ Control.MpTextChatTeam, Key.Y },
			{ Control.MultiplayerInfo, Key.Z },
			{ Control.NextCamera, Key.V },
			// { Control.NextWeapon, Key.b_995 },
			{ Control.ParachuteBrakeLeft, Key.Q },
			{ Control.ParachuteBrakeRight, Key.E },
			// { Control.ParachuteDeploy, Key.b_100 },
			{ Control.ParachuteDetach, Key.F },
			{ Control.ParachutePitchDownOnly, Key.S },
			//{ Control.ParachutePitchUpDown, "t_S%t_W },
			{ Control.ParachutePitchUpOnly, Key.W },
			// { Control.ParachutePrecisionLanding, Key.b_1000 },
			{ Control.ParachuteSmoke, Key.X },
			{ Control.ParachuteTurnLeftOnly, Key.A },
			//{ Control.ParachuteTurnLeftRight, "t_D%t_A },
			{ Control.ParachuteTurnRightOnly, Key.D },
			// { Control.Phone, Key.b_194 },
			{ Control.PhoneCameraDOF, Key.F },
			{ Control.PhoneCameraExpression, Key.X },
			{ Control.PhoneCameraFocusLock, Key.L },
			{ Control.PhoneCameraGrid, Key.G },
			// { Control.PhoneCameraSelfie, Key.b_102 },
			// { Control.PhoneCancel, Key.b_1004 },
			// { Control.PhoneDown, Key.b_195 },
			// { Control.PhoneExtraOption, Key.b_2000 },
			// { Control.PhoneLeft, Key.b_196 },
			// { Control.PhoneOption, Key.b_198 },
			// { Control.PhoneRight, Key.b_197 },
			// { Control.PhoneScrollBackward, Key.b_115 },
			// { Control.PhoneScrollForward, Key.b_116 },
			// { Control.PhoneSelect, Key.b_1003 },
			// { Control.PhoneUp, Key.b_194 },
			{ Control.Pickup, Key.E },
			// { Control.PrevWeapon, Key.b_995 },
			{ Control.PushToTalk, Key.N },
			// { Control.RadioWheelLeftRight, Key.b_112 },
			// { Control.RadioWheelUpDown, Key.b_113 },
			// { Control.RappelJump, Key.b_995 },
			// { Control.RappelLongJump, Key.b_995 },
			// { Control.RappelSmashWindow, Key.b_995 },
			{ Control.Reload, Key.R },
			// { Control.ReplayAdvance, Key.b_197 },
			// { Control.ReplayBack, Key.b_196 },
			// { Control.ReplayCameraDown, Key.b_1010 },
			// { Control.ReplayCameraUp, Key.b_1009 },
			// { Control.ReplayClipDelete, Key.b_198 },
			// { Control.ReplayCtrl, Key.b_1013 },
			{ Control.ReplayCycleMarkerLeft, Key.OpenBrackets },
			{ Control.ReplayCycleMarkerRight, Key.CloseBrackets },
			{ Control.ReplayEndpoint, Key.N },
			// { Control.ReplayFfwd, Key.b_194 },
			// { Control.ReplayFOVDecrease, Key.b_130 },
			// { Control.ReplayFOVIncrease, Key.b_131 },
			{ Control.ReplayHidehud, Key.H },
			// { Control.ReplayMarkerDelete, Key.b_198 },
			{ Control.ReplayNewmarker, Key.M },
			// { Control.ReplayPause, Key.b_2000 },
			// { Control.ReplayPreview, Key.b_2000 },
			// { Control.ReplayPreviewAudio, Key.b_2000 },
			{ Control.ReplayRecord, Key.S },
			{ Control.ReplayRestart, Key.R },
			// { Control.ReplayRewind, Key.b_195 },
			// { Control.ReplaySave, Key.b_174 },
			{ Control.ReplayScreenshot, Key.U },
			{ Control.ReplayShowhotkey, Key.K },
			// { Control.ReplaySnapmaticPhoto, Key.b_1002 },
			{ Control.ReplayStartpoint, Key.B },
			// { Control.ReplayStartStopRecording, Key.b_170 },
			// { Control.ReplayStartStopRecordingSecondary, Key.b_171 },
			{ Control.ReplayTimelineDuplicateClip, Key.C },
			{ Control.ReplayTimelinePickupClip, Key.X },
			{ Control.ReplayTimelinePlaceClip, Key.V },
			// { Control.ReplayTimelineSave, Key.b_174 },
			{ Control.ReplayToggletime, Key.C },
			// { Control.ReplayToggleTimeline, Key.b_199 },
			{ Control.ReplayToggletips, Key.V },
			{ Control.ReplayTools, Key.T },
			// { Control.SaveReplayClip, Key.b_172 },
			// { Control.ScaledLookDownOnly, Key.b_111 },
			// { Control.ScaledLookLeftOnly, Key.b_108 },
			// { Control.ScaledLookLeftRight, Key.b_112 },
			// { Control.ScaledLookRightOnly, Key.b_109 },
			// { Control.ScaledLookUpDown, Key.b_113 },
			// { Control.ScaledLookUpOnly, Key.b_110 },
			// { Control.ScriptedFlyZDown, Key.b_1010 },
			// { Control.ScriptedFlyZUp, Key.b_1009 },
			// { Control.ScriptLB, Key.b_995 },
			//{ Control.ScriptLeftAxisX, "t_D%t_A },
			//{ Control.ScriptLeftAxisY, "t_S%t_W },
			// { Control.ScriptLS, Key.b_995 },
			// { Control.ScriptLT, Key.b_995 },
			{ Control.ScriptPadDown, Key.S },
			{ Control.ScriptPadLeft, Key.A },
			{ Control.ScriptPadRight, Key.D },
			{ Control.ScriptPadUp, Key.W },
			// { Control.ScriptRB, Key.b_995 },
			// { Control.ScriptRDown, Key.b_100 },
			// { Control.ScriptRightAxisX, Key.b_112 },
			// { Control.ScriptRightAxisY, Key.b_113 },
			// { Control.ScriptRLeft, Key.b_1013 },
			// { Control.ScriptRRight, Key.b_101 },
			// { Control.ScriptRS, Key.b_995 },
			// { Control.ScriptRT, Key.b_100 },
			// { Control.ScriptRUp, Key.b_101 },
			{ Control.ScriptSelect, Key.V },
			// { Control.SelectCharacterFranklin, Key.b_175 },
			// { Control.SelectCharacterMichael, Key.b_174 },
			// { Control.SelectCharacterMultiplayer, Key.b_177 },
			// { Control.SelectCharacterTrevor, Key.b_176 },
			// { Control.SelectNextWeapon, Key.b_116 },
			// { Control.SelectPrevWeapon, Key.b_115 },
			// { Control.SelectWeapon, Key.b_1002 },
			{ Control.SelectWeaponAutoRifle, Key.D8 },
			{ Control.SelectWeaponHandgun, Key.D6 },
			{ Control.SelectWeaponHeavy, Key.D4 },
			{ Control.SelectWeaponMelee, Key.D2 },
			{ Control.SelectWeaponShotgun, Key.D3 },
			{ Control.SelectWeaponSmg, Key.D7 },
			{ Control.SelectWeaponSniper, Key.D9 },
			{ Control.SelectWeaponSpecial, Key.D5 },
			{ Control.SelectWeaponUnarmed, Key.D1 },
			// { Control.SkipCutscene, Key.b_100 },
			// { Control.SniperZoom, Key.b_117 },
			// { Control.SniperZoomIn, Key.b_995 },
			// { Control.SniperZoomInAlternate, Key.b_995 },
			// { Control.SniperZoomInOnly, Key.b_115 },
			// { Control.SniperZoomInSecondary, Key.b_115 },
			// { Control.SniperZoomOut, Key.b_995 },
			// { Control.SniperZoomOutAlternate, Key.b_995 },
			// { Control.SniperZoomOutOnly, Key.b_116 },
			// { Control.SniperZoomOutSecondary, Key.b_116 },
			// { Control.SpecialAbility, Key.b_995 },
			// { Control.SpecialAbilityPC, Key.b_1012 },
			{ Control.SpecialAbilitySecondary, Key.B },
			// { Control.Sprint, Key.b_1000 },
			// { Control.SwitchVisor, Key.b_180 },
			{ Control.Talk, Key.E },
			{ Control.ThrowGrenade, Key.G },
			{ Control.VehicleAccelerate, Key.W },
			// { Control.VehicleAim, Key.b_101 },
			// { Control.VehicleAttack, Key.b_100 },
			// { Control.VehicleAttack2, Key.b_1014 },
			{ Control.VehicleBikeWings, Key.X },
			{ Control.VehicleBrake, Key.S },
			{ Control.VehicleCarJump, Key.E },
			{ Control.VehicleCinCam, Key.R },
			// { Control.VehicleCinematicDownOnly, Key.b_116 },
			// { Control.VehicleCinematicLeftRight, Key.b_112 },
			// { Control.VehicleCinematicUpDown, Key.b_113 },
			// { Control.VehicleCinematicUpOnly, Key.b_115 },
			// { Control.VehicleDriveLook, Key.b_100 },
			// { Control.VehicleDriveLook2, Key.b_101 },
			{ Control.VehicleDropProjectile, Key.X },
			{ Control.VehicleDuck, Key.X },
			{ Control.VehicleExit, Key.F },
			// { Control.VehicleFlyAttack, Key.b_2000 },
			// { Control.VehicleFlyAttack2, Key.b_2000 },
			// { Control.VehicleFlyAttackCamera, Key.b_200 },
			{ Control.VehicleFlyBombBay, Key.E },
			// { Control.VehicleFlyBoost, Key.b_1000 },
			{ Control.VehicleFlyCounter, Key.E },
			{ Control.VehicleFlyDuck, Key.X },
			// { Control.VehicleFlyMouseControlOverride, Key.b_100 },
			// { Control.VehicleFlyPitchDownOnly, Key.b_141 },
			//{ Control.VehicleFlyPitchUpDown, "b_141%b_144 },
			// { Control.VehicleFlyPitchUpOnly, Key.b_144 },
			// { Control.VehicleFlyRollLeftOnly, Key.b_140 },
			//{ Control.VehicleFlyRollLeftRight, "b_142%b_140 },
			// { Control.VehicleFlyRollRightOnly, Key.b_142 },
			// { Control.VehicleFlySelectNextWeapon, Key.b_115 },
			{ Control.VehicleFlySelectPrevWeapon, Key.OpenBrackets },
			// { Control.VehicleFlySelectTargetLeft, Key.b_143 },
			// { Control.VehicleFlySelectTargetRight, Key.b_145 },
			{ Control.VehicleFlyThrottleDown, Key.S },
			{ Control.VehicleFlyThrottleUp, Key.W },
			{ Control.VehicleFlyTransform, Key.X },
			{ Control.VehicleFlyUnderCarriage, Key.G },
			{ Control.VehicleFlyVerticalFlightMode, Key.E },
			{ Control.VehicleFlyYawLeft, Key.A },
			{ Control.VehicleFlyYawRight, Key.D },
			{ Control.VehicleGrapplingHook, Key.E },
			// { Control.VehicleGunDown, Key.b_995 },
			// { Control.VehicleGunLeft, Key.b_995 },
			// { Control.VehicleGunLeftRight, Key.b_112 },
			// { Control.VehicleGunRight, Key.b_995 },
			// { Control.VehicleGunUp, Key.b_995 },
			// { Control.VehicleGunUpDown, Key.b_113 },
			// { Control.VehicleHandbrake, Key.b_2000 },
			{ Control.VehicleHeadlight, Key.H },
			{ Control.VehicleHorn, Key.E },
			{ Control.VehicleHotwireLeft, Key.W },
			{ Control.VehicleHotwireRight, Key.S },
			// { Control.VehicleHydraulicsControlDown, Key.b_1013 },
			{ Control.VehicleHydraulicsControlLeft, Key.A },
			//{ Control.VehicleHydraulicsControlLeftRight, "b_1013%b_1000 },
			{ Control.VehicleHydraulicsControlRight, Key.D },
			{ Control.VehicleHydraulicsControlToggle, Key.X },
			// { Control.VehicleHydraulicsControlUp, Key.b_1000 },
			//{ Control.VehicleHydraulicsControlUpDown, "t_D%t_A },
			// { Control.VehicleJump, Key.b_2000 },
			{ Control.VehicleLookBehind, Key.C },
			// { Control.VehicleLookLeft, Key.b_995 },
			// { Control.VehicleLookRight, Key.b_995 },
			{ Control.VehicleMeleeHold, Key.X },
			// { Control.VehicleMeleeLeft, Key.b_100 },
			// { Control.VehicleMeleeRight, Key.b_101 },
			// { Control.VehicleMouseControlOverride, Key.b_100 },
			// { Control.VehicleMoveDown, Key.b_995 },
			// { Control.VehicleMoveDownOnly, Key.b_1013 },
			// { Control.VehicleMoveLeft, Key.b_995 },
			{ Control.VehicleMoveLeftOnly, Key.A },
			//{ Control.VehicleMoveLeftRight, "t_D%t_A },
			// { Control.VehicleMoveRight, Key.b_995 },
			{ Control.VehicleMoveRightOnly, Key.D },
			// { Control.VehicleMoveUp, Key.b_995 },
			//{ Control.VehicleMoveUpDown, "b_1013%b_1000 },
			// { Control.VehicleMoveUpOnly, Key.b_1000 },
			{ Control.VehicleNextRadio, Key.OemPeriod },
			{ Control.VehicleNextRadioTrack, Key.Equals },
			// { Control.VehicleParachute, Key.b_2000 },
			// { Control.VehiclePassengerAim, Key.b_101 },
			// { Control.VehiclePassengerAttack, Key.b_100 },
			{ Control.VehiclePrevRadio, Key.OemComma },
			{ Control.VehiclePrevRadioTrack, Key.Subtract },
			{ Control.VehiclePushbikeFrontBrake, Key.Q },
			{ Control.VehiclePushbikePedal, Key.W },
			{ Control.VehiclePushbikeRearBrake, Key.S },
			// { Control.VehiclePushbikeSprint, Key.b_1012 },
			{ Control.VehicleRadioWheel, Key.Q },
			{ Control.VehicleRocketBoost, Key.E },
			{ Control.VehicleRoof, Key.H },
			// { Control.VehicleSelectNextWeapon, Key.b_115 },
			{ Control.VehicleSelectPrevWeapon, Key.OpenBrackets },
			{ Control.VehicleShuffle, Key.H },
			// { Control.VehicleSlowMoDownOnly, Key.b_116 },
			// { Control.VehicleSlowMoUpDown, Key.b_117 },
			// { Control.VehicleSlowMoUpOnly, Key.b_115 },
			// { Control.VehicleSpecial, Key.b_995 },
			// { Control.VehicleSpecialAbilityFranklin, Key.b_995 },
			// { Control.VehicleStuntUpDown, Key.b_995 },
			// { Control.VehicleSubAscend, Key.b_1000 },
			// { Control.VehicleSubDescend, Key.b_1013 },
			// { Control.VehicleSubMouseControlOverride, Key.b_100 },
			// { Control.VehicleSubPitchDownOnly, Key.b_141 },
			//{ Control.VehicleSubPitchUpDown, "b_141%b_144 },
			// { Control.VehicleSubPitchUpOnly, Key.b_144 },
			{ Control.VehicleSubThrottleDown, Key.S },
			{ Control.VehicleSubThrottleUp, Key.W },
			{ Control.VehicleSubTurnHardLeft, Key.A },
			{ Control.VehicleSubTurnHardRight, Key.D },
			// { Control.VehicleSubTurnLeftOnly, Key.b_140 },
			//{ Control.VehicleSubTurnLeftRight, "b_142%b_140 },
			// { Control.VehicleSubTurnRightOnly, Key.b_142 },
			// { Control.WeaponSpecial, Key.b_995 },
			{ Control.WeaponSpecial2, Key.E },
			//{ Control.WeaponWheelLeftRight, "b_-1 },
			// { Control.WeaponWheelNext, Key.b_116 },
			// { Control.WeaponWheelPrev, Key.b_115 },
			//{ Control.WeaponWheelUpDown, "b_-1 },
			// { Control.Whistle, Key.b_995 },
		};

		public static Dictionary<string, Key> KeyMappings = new Dictionary<string, Key>
		{
			//{ "b_-1 },
			//{ "b_100", Key.b_100 },
			//{ "b_1000", Key.b_1000 },
			//{ "b_1002", Key.b_1002 },
			//{ "b_1003", Key.b_1003 },
			//{ "b_1004", Key.b_1004 },
			//{ "b_1008", Key.b_1008 },
			//{ "b_1009", Key.b_1009 },
			//{ "b_101", Key.b_101 },
			//{ "b_1010", Key.b_1010 },
			//{ "b_1012", Key.b_1012 },
			//{ "b_1013", Key.b_1013 },
			//{ "b_1014", Key.b_1014 },
			//{ "b_1015", Key.b_1015 },
			//{ "b_102", Key.b_102 },
			//{ "b_108", Key.b_108 },
			//{ "b_109", Key.b_109 },
			//{ "b_110", Key.b_110 },
			//{ "b_111", Key.b_111 },
			//{ "b_112", Key.b_112 },
			//{ "b_113", Key.b_113 },
			//{ "b_115", Key.b_115 },
			//{ "b_116", Key.b_116 },
			//{ "b_117", Key.b_117 },
			//{ "b_130", Key.b_130 },
			//{ "b_131", Key.b_131 },
			//{ "b_140", Key.b_140 },
			//{ "b_141", Key.b_141 },
			//{ "b_142", Key.b_142 },
			//{ "b_143", Key.b_143 },
			//{ "b_144", Key.b_144 },
			//{ "b_145", Key.b_145 },
			//{ "b_170", Key.b_170 },
			//{ "b_171", Key.b_171 },
			//{ "b_172", Key.b_172 },
			//{ "b_174", Key.b_174 },
			//{ "b_175", Key.b_175 },
			//{ "b_176", Key.b_176 },
			//{ "b_177", Key.b_177 },
			//{ "b_178", Key.b_178 },
			//{ "b_179", Key.b_179 },
			//{ "b_180", Key.b_180 },
			//{ "b_194", Key.b_194 },
			//{ "b_195", Key.b_195 },
			//{ "b_196", Key.b_196 },
			//{ "b_197", Key.b_197 },
			//{ "b_198", Key.b_198 },
			//{ "b_199", Key.b_199 },
			//{ "b_200", Key.b_200 },
			//{ "b_2000", Key.b_2000 },
			//{ "b_995", Key.b_995 },
			{ "t_-", Key.Subtract },
			{ "t_,", Key.OemComma },
			{ "t_;", Key.OemSemicolon },
			{ "t_.", Key.OemPeriod },
			{ "t_[", Key.OpenBrackets },
			{ "t_]", Key.CloseBrackets },
			{ "t_`", Key.Backtick },
			{ "t_=", Key.Equals },
			{ "t_1", Key.D1 },
			{ "t_2", Key.D2 },
			{ "t_3", Key.D3 },
			{ "t_4", Key.D4 },
			{ "t_5", Key.D5 },
			{ "t_6", Key.D6 },
			{ "t_7", Key.D7 },
			{ "t_8", Key.D8 },
			{ "t_9", Key.D9 },
			{ "t_A", Key.A },
			{ "t_B", Key.B },
			{ "t_C", Key.C },
			{ "t_D", Key.D },
			{ "t_E", Key.E },
			{ "t_F", Key.F },
			{ "t_G", Key.G },
			{ "t_H", Key.H },
			{ "t_K", Key.K },
			{ "t_L", Key.L },
			{ "t_M", Key.M },
			{ "t_N", Key.N },
			{ "t_P", Key.P },
			{ "t_Q", Key.Q },
			{ "t_R", Key.R },
			{ "t_S", Key.S },
			{ "t_T", Key.T },
			{ "t_U", Key.U },
			{ "t_V", Key.V },
			{ "t_W", Key.W },
			{ "t_X", Key.X },
			{ "t_Y", Key.Y },
			{ "t_Z", Key.Z },
		};
	}
}
