-- FX resource definition
-- This file is automatically generated with `nfpm install` - any manual changes will be lost

fx_version 'cerulean'
game 'gta5'

server_scripts {
	-- NFive
	'NFive.Server.net.dll',
}

client_scripts {
	-- NFive
	'NFive.Client.net.dll',
}

files {
	-- NFive
	'DotNetZip.dll',
	'Newtonsoft.Json.dll',
	'NGettext.dll',
	'System.ComponentModel.DataAnnotations.dll',
	'NFive.SDK.Core.net.dll',
	'NFive.SDK.Client.net.dll',
	'index.html',
}

-- NFive
ui_page 'index.html'
